function createfigureRegionIntensity(YMatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 24-Apr-2018 15:15:15

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'XTickLabel',{'OL','VLNP','VMNP','AL','MB','LH','SNP','CX','LX','INP','PENP','GNG'},...
    'XTick',[1 2 3 4 5 6 7 8 9 10 11 12]);
hold(axes1,'on');

% Create ylabel
ylabel({'Normalized intensity'});

% Create multiple lines using matrix input to plot
plot(YMatrix1,'Marker','+','LineWidth',2,'LineStyle','none','Parent',axes1);

